#!/bin/bash

echo "export PATH=~/.local/bin:$PATH"

sudo rm -r ~/.vault-token

docker run --rm -v $HOME/data -it ${_DOCKER_IMAGE_TAG} /get-aws-sts-token.sh ${_VAULT_URI_GAMMA} ${_LDAP_USERNAME}

echo "ok!!"
